# Generated by Django 5.0.2 on 2024-03-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeber',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='memeber',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
